version: "3.5"

services:
  postgres-db:
    image: postgres:latest
    hostname: postgres-db
    container_name: db-postgres
    expose:
        - "5432"
    ports:
        - "5432:5432"
    networks:
        - default
    user: "1001:1001"
    environment:
        - "POSTGRES_PASSWORD=password"
        - "POSTGRES_USER=postgres"
        - "POSTGRES_DB=postgres"
        - "PGDATA=/pgdata"
    volumes:
      - /home/ubuntu/postgres-monday19:/pgdata

      